server:
  port: 15200
spring:
  application:
    name: chendeyin-cloud-basicdata  # 服务间调用所使用的名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_test?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
        min-idle: 10


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
#
#eureka:
#  instance:
#    hostname: http://127.0.0.1
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/