server:
  port: 8769
spring:
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-b/**
      serviceId: basicData
    api-b:
      path: /api-p/**
      serviceId: peopleManage